# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Mykhailo Datsyk
# Contact: https://www.linkedin.com/in/mykhailo-datsyk/
#
# YOU SHOULD MERGE these entries into your tk-app yaml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get cinema engine up and running with the 
# default tk-apps for this environment

################################################################################

# -- Cinema

# asset step
settings.tk-multi-snapshot.cinema.asset_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-cinema.py"
  template_snapshot: cinema_asset_snapshot
  template_work: cinema_asset_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"

# sequence step
settings.tk-multi-snapshot.cinema.sequence_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-cinema.py"
  template_snapshot: cinema_sequence_snapshot
  template_work: cinema_sequence_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.cinema.shot_step:
  hook_scene_operation: "{engine}/tk-multi-snapshot/scene_operation_tk-cinema.py"
  template_snapshot: cinema_shot_snapshot
  template_work: cinema_shot_work
  hook_thumbnail: "{engine}/thumbnail.py"
  location: "@apps.tk-multi-snapshot.location"


################################################################################
